### ISSUE TITLE
Issue with ansible-container 0.9.2 and docker 3.1.1

### ISSUE THREAD

**Issue by ops75** [aric49/ansible_container_lab#2]
By default when installing ansible-container using pip or pipenv the version of docker that gets installed is 3.1.1. There are numerous issues that lead to failed `ansible-container build` calls with this combination. Specifying the 2.7 version of docker resolves all those issues: `pipenv install docker==2.7 ansible-container`

Checking the setup.py included in the ansible-container source it specifies: `'docker': ['docker>=2.4.0,<3.0']`

**Comment by aric49** [comment]
Good catch @greg75  ---  I think this was something that I missed when writing the book, and came to light once Docker upgraded their Pip packages.   Let me validate your workaround and ensure it's working.  Thank you for reporting this issue, I'll be sure to push a fix ASAP.

**Comment by aric49** [comment]
@greg75  -  I took a quick peek at the current Vagrant environment (cloned the repo fresh, ran `vagrant up`).   The `ansible-container build` issue I am seeing is as follows, not sure if this is what you're seeing or not:

```
vagrant@node01:/vagrant/AnsibleContainer/nginx_demo$ ansible-container build
ERROR   Unknown exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container/cli.py", line 299, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/usr/local/lib/python2.7/dist-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/container/core.py", line 158, in hostcmd_build
    conductor_container_id = engine_obj.get_container_id_for_service('conductor')
  File "/usr/local/lib/python2.7/dist-packages/container/docker/engine.py", line 527, in get_container_id_for_service
    container_info = self.client.containers.get(self.container_name_for_service(service_name))
  File "/usr/local/lib/python2.7/dist-packages/container/docker/engine.py", line 164, in client
    self._client = docker.from_env(version='auto', timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 81, in from_env
    **kwargs_from_env(**kwargs))
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 38, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 149, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 176, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
DockerException: Error while fetching server API version: ('Connection aborted.', error(13, 'Permission denied'))
```

To attempt to remedy this, I tried uninstalling the `docker` pip package and replacing it with the version you recommended:  `2.7`.   I attempted this using `pipenv` as well as `virtualenv`.  In all of these cases, I got the same error above. 

If this is the issue you're seeing, I believe it is caused by a recent Vagrant box update. It appears the Vagrant box is now using the user `vagrant` instead of the user `ubuntu`.  In the Vagrantfile, I have it setup to grant `ubuntu` privileges in the Docker group, so that the user can interact with the Docker daemon without requiring elevated privileges.  However, with the most recent Vagrant box update, the default user is now `vagrant` which does not have permissions to interact with the Docker daemon. 

As a fix, I added a new line in the Vagrant provisioning steps so that the user `vagrant` is granted permissions to run commands against the Docker daemon:

`usermod -aG docker vagrant`

Do a `git pull` on the master branch of this repo, relaunch the Vagrant box and let me know if that fixes your issue.


If you are seeing another issue, please let me know what error you're seeing and what steps are required to re-create it.  Thanks for taking the time to open an issue :-D

**Comment by ops75** [comment]
I am running all this on a bare-metal install of Ubuntu 16.04.4, not Vagrant. Here is the specific error I am seeing that is remedied by specifying the version of docker to 2.7 when installing ansible-container:

```
$ pipenv install ansible-container[docker]

$ pipenv graph
ansible-container==0.9.2                                      
  - Jinja2 [required: >=2.9, installed: 2.10]                 
    - MarkupSafe [required: >=0.23, installed: 1.0]           
  - pip [required: >=6.0, installed: 9.0.2]                   
  - PyYAML [required: >=3.12, installed: 3.12]                
  - requests [required: >=2, installed: 2.18.4]               
    - certifi [required: >=2017.4.17, installed: 2018.1.18]   
    - chardet [required: <3.1.0,>=3.0.2, installed: 3.0.4]    
    - idna [required: >=2.5,<2.7, installed: 2.6]             
    - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]     
  - ruamel.yaml [required: >=0.14.2, installed: 0.15.37]      
  - six [required: >=1.10, installed: 1.11.0]                 
  - structlog [required: >=16.1, installed: 18.1.0]           
    - six [required: Any, installed: 1.11.0]                  
colorama==0.3.9                                               
docker==3.1.4                                                 
  - docker-pycreds [required: >=0.2.2, installed: 0.2.2]      
    - six [required: >=1.4.0, installed: 1.11.0]              
  - requests [required: !=2.18.0,>=2.14.2, installed: 2.18.4] 
    - certifi [required: >=2017.4.17, installed: 2018.1.18]   
    - chardet [required: <3.1.0,>=3.0.2, installed: 3.0.4]    
    - idna [required: >=2.5,<2.7, installed: 2.6]             
    - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]     
  - six [required: >=1.4.0, installed: 1.11.0]                
  - websocket-client [required: >=0.32.0, installed: 0.47.0]  
    - six [required: Any, installed: 1.11.0]

$ ansible-container init && ansible container-build
Ansible Container initialized.
Building Docker Engine context...                                                                                                        
Starting Docker build of Ansible Container Conductor image (please be patient)...                                                        
ERROR   Unknown exception                                                                                                                
Traceback (most recent call last):                                                                                                       
  File "/home/greg/.local/share/virtualenvs/test-MHwE218n/lib/python3.5/site-packages/container/cli.py", line 299, in __call__           
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))                                                                   
  File "/home/greg/.local/share/virtualenvs/test-MHwE218n/lib/python3.5/site-packages/container/__init__.py", line 28, in __wrapped__    
    return fn(*args, **kwargs)                                                                                                           
  File "/home/greg/.local/share/virtualenvs/test-MHwE218n/lib/python3.5/site-packages/container/core.py", line 181, in hostcmd_build     
    environment=env_vars                                                                                                                 
  File "/home/greg/.local/share/virtualenvs/test-MHwE218n/lib/python3.5/site-packages/container/docker/engine.py", line 105, in __wrapped
__                                                                                                                                       
    return fn(self, *args, **kwargs)                                                                                                     
  File "/home/greg/.local/share/virtualenvs/test-MHwE218n/lib/python3.5/site-packages/container/__init__.py", line 28, in __wrapped__    
    return fn(*args, **kwargs)                                                                                                           
  File "/home/greg/.local/share/virtualenvs/test-MHwE218n/lib/python3.5/site-packages/container/docker/engine.py", line 1070, in build_co
nductor_image                                                                                                                            
    return image.id                                                                                                                      
AttributeError: 'tuple' object has no attribute 'id'    
```

**Comment by aric49** [comment]
I was able to re-create the error you are seeing on a fresh Ubuntu 16.04 EC2 micro instance.   You can read the full output of my experiment here:  https://gist.github.com/aric49/bf4bef03acd1a13e8f8b850714d19508

I installed Ansible Container using standard `pip install`, not `pipenv`, and I am seeing that the version of Docker getting installed in my instance is:  2.4.0, not 3.X as you are observing. It's also strange I am not seeing this same issue happening in my Vagrant lab.   Really peculiar. 

Unfortunately, I'm not sure I have a good answer for you at the moment.   Have you tried opening an issue over at the Ansible Container git repo? It's possible this is a bug they might already know about. (https://github.com/ansible/ansible-container)  I know j00bar and chousknecht are super responsive and should be able to get this squared away. 

When I get some free time after work, I'll try hacking away on it to see if I can get to the bottom of it. Thank you for your patience.
